name: ZoltanGal
favicon: null
layout_spectrum: 0.96402
typography_spectrum: 0.62299
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ef0009'
    - '#ffffff'
    - '#ee686d'
    - '#eea3a2'
    - '#c32d34'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
