name: ZoltanGal
favicon: null
layout_spectrum: 0.28125642612576485
typography_spectrum: 0.11954186833463609
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#493806'
    - '#8d7c0f'
    - '#b6a142'
    - '#f5ea82'
  brandStrength: 0.625
  lightness: 0.8125
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
